-- Run in Supabase SQL editor if notifications are not created yet.
-- In-app notifications for connection requests, accepts, and post engagement.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  meta jsonb default '{}'::jsonb
);

create index if not exists notifications_user_id_created_at_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id)
  where read_at is null;

alter table public.notifications enable row level security;

-- Service role bypasses RLS; anon users have no direct access (app uses API + service role).
