-- Project interest / teammate applications (in-app, not email).
-- Run in Supabase SQL editor after reviewing.

create table if not exists public.project_interests (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  applicant_id bigint not null references public.users (id) on delete cascade,
  message text,
  status text not null default 'pending' check (status in ('pending', 'withdrawn', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (project_id, applicant_id)
);

create index if not exists project_interests_project_id_idx
  on public.project_interests (project_id);

create index if not exists project_interests_applicant_id_idx
  on public.project_interests (applicant_id);

create index if not exists project_interests_owner_pending_idx
  on public.project_interests (project_id)
  where status = 'pending';

alter table public.project_interests enable row level security;

-- App uses service role for writes; optional policies can be added for direct client access later.
