-- Trust: moderators, user reports, blocks. Run in Supabase SQL editor.

alter table public.users
  add column if not exists is_moderator boolean not null default false;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references public.users (id) on delete cascade,
  target_type text not null check (target_type in ('user', 'post', 'project', 'message')),
  target_id bigint not null,
  reason text not null,
  details text,
  status text not null default 'open' check (status in ('open', 'dismissed', 'resolved')),
  moderator_notes text,
  handled_by bigint references public.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_created_at_idx on public.reports (created_at desc);

create table if not exists public.blocks (
  blocker_id bigint not null references public.users (id) on delete cascade,
  blocked_id bigint not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create index if not exists blocks_blocked_idx on public.blocks (blocked_id);

alter table public.reports enable row level security;
alter table public.blocks enable row level security;
