-- Direct messaging between users.

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  participant_low_id bigint not null references public.users (id) on delete cascade,
  participant_high_id bigint not null references public.users (id) on delete cascade,
  updated_at timestamptz not null default now(),
  check (participant_low_id < participant_high_id),
  unique (participant_low_id, participant_high_id)
);

create index if not exists conversations_low_idx on public.conversations (participant_low_id);
create index if not exists conversations_high_idx on public.conversations (participant_high_id);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id) on delete cascade,
  sender_id bigint not null references public.users (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists direct_messages_conversation_idx
  on public.direct_messages (conversation_id, created_at desc);

alter table public.conversations enable row level security;
alter table public.direct_messages enable row level security;
