-- Groups: communities with membership, join requests, scoped posts and project listings.
-- Run in Supabase SQL editor after reviewing.

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  created_by bigint not null references public.users (id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists groups_created_at_idx on public.groups (created_at desc);

create table if not exists public.group_memberships (
  group_id bigint not null references public.groups (id) on delete cascade,
  user_id bigint not null references public.users (id) on delete cascade,
  role text not null check (role in ('owner', 'moderator', 'member')),
  created_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create index if not exists group_memberships_user_id_idx on public.group_memberships (user_id);

create table if not exists public.group_join_requests (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups (id) on delete cascade,
  applicant_id bigint not null references public.users (id) on delete cascade,
  message text,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'withdrawn')),
  created_at timestamptz not null default now(),
  reviewed_by bigint references public.users (id) on delete set null,
  reviewed_at timestamptz,
  unique (group_id, applicant_id)
);

create index if not exists group_join_requests_group_pending_idx
  on public.group_join_requests (group_id)
  where status = 'pending';

alter table public.groups enable row level security;
alter table public.group_memberships enable row level security;
alter table public.group_join_requests enable row level security;

-- App uses service role for writes; optional client policies can be added later.

alter table public.posts add column if not exists group_id bigint references public.groups (id) on delete cascade;

create index if not exists posts_group_id_idx on public.posts (group_id) where group_id is not null;

alter table public.projects add column if not exists group_id bigint references public.groups (id) on delete cascade;

create index if not exists projects_group_id_idx on public.projects (group_id) where group_id is not null;
