-- Multi-audience post visibility (OR semantics). Run after 007_groups.sql.

create table if not exists public.post_visibility (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  scope text not null check (scope in ('public', 'connections', 'private', 'group')),
  group_id bigint references public.groups (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint post_visibility_group_id_check check (
    (scope = 'group' and group_id is not null)
    or (scope <> 'group' and group_id is null)
  )
);

create index if not exists post_visibility_post_id_idx on public.post_visibility (post_id);
create index if not exists post_visibility_group_idx
  on public.post_visibility (group_id)
  where scope = 'group';

-- At most one row per post for non-group scopes; one row per (post, group) for group scope.
create unique index if not exists post_visibility_unique_non_group
  on public.post_visibility (post_id, scope)
  where scope in ('public', 'connections', 'private');

create unique index if not exists post_visibility_unique_group
  on public.post_visibility (post_id, group_id)
  where scope = 'group';

alter table public.post_visibility enable row level security;

create policy post_visibility_select_all on public.post_visibility
  for select using (true);

-- Backfill from legacy posts.audience + posts.group_id
insert into public.post_visibility (post_id, scope, group_id)
select p.id,
  case
    when p.audience = 'group' then 'group'
    else p.audience
  end,
  case when p.audience = 'group' then p.group_id else null end
from public.posts p
where p.audience in ('public', 'connections', 'private', 'group')
  and not exists (select 1 from public.post_visibility pv where pv.post_id = p.id)
  and (p.audience <> 'group' or p.group_id is not null);

-- Posts that were multi or unknown audience: default to public if still missing
insert into public.post_visibility (post_id, scope, group_id)
select p.id, 'public', null
from public.posts p
where not exists (select 1 from public.post_visibility pv where pv.post_id = p.id);
